"""Puertos mínimos usados por los casos de uso de suscripciones.

Esta capa aplica Dependency Inversion (DIP): los servicios describen las
capacidades que necesitan mediante ``Protocol`` y no importan repositorios JSON
ni implementaciones de billetera. Python usa tipado estructural, por lo que las
clases existentes cumplen estos contratos sin heredar de ellas.
"""

from typing import Protocol


class RepositorioSuscripciones(Protocol):
    def agregar_sin_guardar(self, suscripcion, viajes): ...
    def listar_suscripciones(self, id_pasajero=None): ...
    def listar_viajes(self, id_pasajero=None, id_suscripcion=None): ...
    def obtener_suscripcion(self, id_suscripcion): ...
    def obtener_viaje(self, id_viaje): ...
    def listar_viajes_conductor(self, id_conductor, estados=None): ...
    def listar_suscripciones_conductor(self, id_conductor, estados=None): ...
    def crear_snapshot(self): ...
    def restaurar_snapshot(self, snapshot): ...
    def guardar_cambios(self): ...


class PasarelaPagosSuscripcion(Protocol):
    """Puerto ISP: solo contiene movimientos monetarios de suscripciones."""

    def cobrar_suscripcion(self, usuario, monto): ...
    def reembolsar_suscripcion(self, usuario, monto): ...
    def abonar_conductor_suscripcion(self, conductor, monto): ...


class SelectorOfertas(Protocol):
    def seleccionar_ids(self, catalogo): ...


class FabricaUnidadTrabajo(Protocol):
    def __call__(self): ...
